### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by bgabor78** [davedash/mysql-anonymous#10]
I have actualized the code for python3.
See the attached file.
[anonymize.zip](https://github.com/davedash/mysql-anonymous/files/4956113/anonymize.zip)

**Comment by RebornX10** [comment]
@bgabor78 It doesn't work anymore, i get a 
```
Traceback (most recent call last):
  File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 114, in <module>
    anonymize(cfg)
  File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 88, in anonymize
    sql.extend(get_deletes(config))
  File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 25, in get_deletes
    for table, data in tables.items():
AttributeError: 'list' object has no attribute 'items'
```
The line being ``for table, data in tables.items():``

Do you, by any chances happen to have a fix?

**Comment by bgabor78** [comment]
> @bgabor78 It doesn't work anymore, i get a
> 
> ```
> Traceback (most recent call last):
>   File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 114, in <module>
>     anonymize(cfg)
>   File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 88, in anonymize
>     sql.extend(get_deletes(config))
>   File "/Users/samueladone/Documents/Satelia/ano_db/db_ano/ano_script.py", line 25, in get_deletes
>     for table, data in tables.items():
> AttributeError: 'list' object has no attribute 'items'
> ```
> 
> The line being `for table, data in tables.items():`
> 
> Do you, by any chances happen to have a fix?

There is an error in your yaml configuration: there is no table in it. Please check if there is any table in database section and check the file format in a yaml validator tool.

**Comment by RebornX10** [comment]
thanks! the update changed the syntax of the yaml, not by a lot but still changed a bit. Instead of 
```yml
database:
    database_name:
         tables:
             table_name: 
                    function_name:
                        - column_name
```
It's now 
```yml
database:
         tables:
            table_name:
                   function_name:
                            - column_name
```
The ```database_name``` is what wasn't working!

Thanks a lot!
